/* Place the page name constants here */

export const ACCOUNT_SCREEN = 'ACCOUNT_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN';
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';
export const ENABLE_BIOMETRICS_SCREEN = 'ENABLE_BIOMETRICS_SCREEN';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';
export const PAYMENT_CARD_DETAILS = 'PAYMENT_CARD_DETAILS';
